<?php
$config['sender']='ottofonf@gmail.com';
$config['receiver']='ottofonf@gmail.com,ottofonf@rambler.ru';
$config['cache']='1';
$config['redirects']='0';
$config['editable']='1';
$config['dummy']='0';
$config['uploader']='1';
$config['robokassa_login']='';
$config['robokassa_password1']='';
$config['robokassa_password2']='';
$config['yandex_user']='';
$config['yandex_key']='';
$config['sitemap_generation']='1';
?>